main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('supplychain/', include('supplychain.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supplychain/urls.py
from django.urls import path
from . import views

app_name = 'supplychain'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('table/', views.table, name='table'),
    path('charts/', views.charts, name='charts'),
    path('airpollution_table_data', views.airpollution_table_data,
         name='airpollution_table_data'),
    path('airpollution_visual_data1', views.airpollution_visual_data1,
         name='airpollution_visual_data1'),
    path('airpollution_visual_data2', views.airpollution_visual_data2,
         name='airpollution_visual_data2'),
    path('temp_country_creator', views.temp_country_creator,
         name='temp_country_creator'),
    path('temp_add_colors_to_pollutants', views.temp_add_colors_to_pollutants,
         name='temp_add_colors_to_pollutants'),
]

templates/airpollution/charts.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Visuals-->
<div class="row">
    <div id="visuals-container" class="col-lg-8 mx-auto">
        <div class="row">
            <div class="col-12 col-md-6">
                <select class="form-control" id="chart2-summary-type">
          <option value="max">Maximum</option>
          <option value="min">Minimum</option>
          <option value="avg">Average</option>
        </select>
            </div>
            <div class="col-12 col-md-6">
                <select class="form-control" id="chart2-pollutant">
          {% for pollutant in pollutant_list %}
          <option value={{ pollutant }}>{{ pollutant }}</option>
          {% endfor %}
        </select>
            </div>
        </div>
        <div id="chart2"></div>
    </div>
</div>
{% endblock %} {% block js %}
<!-- Page level plugins -->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

<script>
    function renderChart(chart_type, canvas, name, labels, datasets) {
        let scales = {};
        if (chart_type === "bar") {
            scales = {
                xAxes: [{
                    stacked: true,
                }, ],
                yAxes: [{
                    stacked: true,
                }, ],
            };
        } else if (chart_type === "line") {
            scales = {
                xAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: "Month",
                    },
                }, ],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: "Value",
                    },
                }, ],
            };
        }
        myChart = new Chart(canvas, {
            type: chart_type,
            data: {
                labels: labels,
                datasets: datasets,
            },
            options: {
                title: {
                    display: true,
                    text: name,
                },
                tooltips: {
                    mode: "index",
                    intersect: false,
                    position: "nearest",
                },
                responsive: true,
                scales: scales,
            },
        });
    }

    $(document).ready(function() {
        $.get("/supplychain/airpollution_visual_data1", function(data) {
            for (const [chart_name, d] of Object.entries(data)) {
                let canvas = $("<canvas />")
                    .addClass("mb-3")
                    .attr("width", "400")
                    .attr("height", "350");
                $("#visuals-container").append(canvas);
                renderChart("bar", canvas, chart_name, d.labels, d.datasets);
            }
        });

        let loadChart2 = function(summary_type, pollutants) {
            $.get(
                `/supplychain/airpollution_visual_data2?summary_type=${summary_type}&pollutant=${pollutants}`,
                function(data) {
                    let canvas = $("<canvas />")
                        .addClass("mb-3")
                        .attr("width", "400")
                        .attr("height", "350");
                    $("#chart2").html(canvas);
                    renderChart("line", canvas, data.name, data.labels, data.datasets);
                }
            );
        };

        loadChart2("max", "PM10");
        $("#chart2-summary-type, #chart2-pollutant").on("change", function() {
            let summary_type = $("#chart2-summary-type").val();
            let pollutant = $("#chart2-pollutant").val();
            loadChart2(summary_type, pollutant);
        });
    });
</script>

{% endblock %}

templates/airpollution/table.html
{% extends 'base.html' %} {% load static %} {% block head %}
<!-- Custom styles for this page -->
<link
  href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}"
  rel="stylesheet"
/>
{% endblock %} {% block content %}

<!-- Table-->
<div class="row">
  <div class="col-lg-8 mx-auto">
    <table id="our-table" class="table">
      <thead>
        <tr>
          <th scope="col">Pollutant</th>
          <th scope="col">Country</th>
          <th scope="col">Avg</th>
          <th scope="col">Min</th>
          <th scope="col">Max</th>
          <th scope="col">Limit</th>
          <th scope="col">Units</th>
        </tr>
      </thead>
      <tbody id="table-body"></tbody>
    </table>
  </div>
</div>

{% endblock %} {% block js %}
<!-- Page level plugins -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<script>
  $(document).ready(function () {
    $.get("/supplychain/airpollution_table_data", function (data) {
      for (const [pollution_name, pollution_data] of Object.entries(data)) {
        for (const [country_iso, d] of Object.entries(pollution_data)) {
          let tr = $("<tr />");
          tr.append($("<th />", { text: pollution_name }));
          tr.append($("<td />", { text: country_iso }));
          tr.append($("<td />", { text: d.avg.toFixed(2) }));
          tr.append($("<td />", { text: d.min.toFixed(2) }));
          tr.append($("<td />", { text: d.max.toFixed(2) }));
          tr.append($("<td />", { text: d.limit }));
          tr.append($("<td />", { text: d.units }));
          $("#table-body").append(tr);
        }
      }
      $("#our-table").DataTable();
    });
  });
</script>
{% endblock %}

templates/airpollution/upload.html
{% extends 'base.html' %} {% block content %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Upload</h1>
</div>

<!-- Upload File Section Form-->
<div class="row">
    <div class="col-lg-8 mx-auto">
        <form id="upload-file" name="upload-file" enctype="multipart/form-data" method="POST" action="{% url 'supplychain:upload' %}">
            {% csrf_token %}
            <div class="control-group">
                <div class="form-group controls mb-0 pb-2">
                    <label>Year</label>
                    <input class="form-control" id="year" name="year" type="number" placeholder="Year" required="required" data-validation-required-message="" />
                    <p class="help-block text-danger"></p>
                </div>
            </div>
            <div class="control-group">
                <div class="form-group controls mb-0 pb-2">
                    <label>File</label>
                    <input class="form-control" id="file" name="file" type="file" required="required" data-validation-required-message="" />
                    <p class="help-block text-danger"></p>
                </div>
            </div>
            <br />

            <div id="success">{{ message_success }}</div>
            <div class="form-group">
                <button class="btn btn-primary btn-xl" id="upload" type="submit">
          Upload
        </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/airpollution/welcome.html
{% extends 'base.html' %} 
{% load static%} 

   
   {% comment %} <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
   <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script> {% endcomment %}
   
  
   {% comment %} <script src="http://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css></script>
   <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script> {% endcomment %}

   
  <!-- Custom styles for this page -->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">


{% block content %}
<!-- Upload File Section-->


<section class="page-section mt-5" id="import-form">
  <div class="container">
    <!-- Upload Section Heading-->
    <h2
      class="page-section-heading text-center text-uppercase text-secondary mb-0"
    >
      Upload Data
    </h2>
    <!-- Icon Divider-->
    <div class="divider-custom">
      <div class="divider-custom-line"></div>
      <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
      <div class="divider-custom-line"></div>
    </div>
    <!-- Upload Data Section Form-->
    <div class="row justify-content-center">
      <div class="col-lg-8 col-xl-7">
        <form id="upload-file" name="upload-file",
              enctype="multipart/form-data" method="POST" action="{% url 'supplychain:airpollution' %}">
          {% csrf_token %}
          <!-- Year input-->
          <div class="form-floating mb-3">
            <input
              class="form-control"
              id="year"
              name="year"
              type="number"
              placeholder="year"
              data-sb-validations="required"
            />
            <label>Year</label>
            <div class="invalid-feedback" data-sb-feedback="name:required">
              A name is required.
            </div>
          </div>
          <!-- Data input-->
          <div class="form-floating mb-3">
            <input
              class="form-control"
              id="file"
              name="file"
              type="file"
              data-sb-validations="required"
            />
            <label>File</label>
            <div class="invalid-feedback" data-sb-feedback="email:required">
              An email is required.
            </div>
            <div class="invalid-feedback" data-sb-feedback="email:email">
              Email is not valid.
            </div>
          </div>
          <!-- Submit success message-->


                        <div class="form-group">
                            <button class="btn btn-primary btn-xl" id="upload" type="submit">Upload</button>
                        </div>

        </form>
      </div>
    </div>
  </div>
</section>

 <!-- Table Section-->

 {% block head %}
    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

 <section class="page-section mt-5" id="data-table">
  <div class="container">
      <!-- Heading-->
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Data Table</h2>
      <!-- Icon Divider-->
      <div class="divider-custom">
          <div class="divider-custom-line"></div>
          <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
          <div class="divider-custom-line"></div>
      </div>
      <!-- Table-->
      <div class="row">
          <div class="col-lg-8 mx-auto">

              <table id="our-table" class="table">
                  <thead>
                  <tr>
                      <th scope="col">Pollutant</th>
                      <th scope="col">Country</th>
                      <th scope="col">Avg</th>
                      <th scope="col">Min</th>
                      <th scope="col">Max</th>
                      <th scope="col">Limit</th>
                      <th scope="col">Units</th>
                  </tr>
                  </thead>
                  <tbody id="table-body">

                  </tbody>
              </table>

          </div>
      </div>
  </div>
</section>


{% endblock %} 

{% block js %}


<!-- Page level plugins -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>



<script>
  $(document).ready(function () {
      $.get("airpollution_table_data", function (data) {
          for (const [pollution_name, pollution_data] of Object.entries(data)) {
              for (const [country_iso, d] of Object.entries(pollution_data)) {
                  let tr = $('<tr />')
                  tr.append($('<th />', {text: pollution_name}))
                  tr.append($('<td />', {text: country_iso}))
                  tr.append($('<td />', {text: d.avg.toFixed(2)}))
                  tr.append($('<td />', {text: d.min.toFixed(2)}))
                  tr.append($('<td />', {text: d.max.toFixed(2)}))
                  tr.append($('<td />', {text: d.limit}))
                  tr.append($('<td />', {text: d.units}))
                  $('#table-body').append(tr)
              }
          }
          $('#our-table').DataTable();
      });
  })
</script>
 
{% endblock %}